NR_ACTIVE_CONNECTIONS = 10
ACTIVE_HOST = None
NR_MAX_LINKS = 11
STATE_SIZE = NR_ACTIVE_CONNECTIONS * 2 + NR_MAX_LINKS + 2
EPOCH_SIZE = 10000
NUMBER_OF_HOSTS = 13
NUMBER_OF_PATHS = 5
NUMBER_OF_AGENTS = 25